<?xml version="1.0" standalone="yes"?>

<!DOCTYPE Helpfile [

<!--
	Comment goes here, as soon as I understand the file structure
-->

    <!ELEMENT Helpfile (TOC,Chapter+,Node*)>

    <!ELEMENT TOC (#PCDATA)>
    
    <!ELEMENT Chapter (Title,Text,Node*)>
    <!ELEMENT Node (Title,Text,Node*)>
  	
    <!ELEMENT Title (#PCDATA)>
    <!ELEMENT Text (#PCDATA)>
]>


<Helpfile>
  <TOC>Contents</TOC>
  
  <Chapter>

    <Title>Introduction</Title>
    <Text>What it's about and maybe an overview about what this documentation covers.</Text>

  </Chapter>

  <Chapter>

    <Title>Installation</Title>
    <Text>Blah...</Text>

    <Node>
      <Title>Requirements</Title>
      <Text>Java, Java3D, available there.</Text>
    </Node>

    <Node>
      <Title>Download</Title>
      <Text>Download the Source or the .jar file here.</Text>
    </Node>

    <Node>
      <Title>Compilation</Title>
      <Text>If you haven't already downloaded the Jar, do this...</Text>
    </Node>

    <Node>
      <Title>Installation</Title>
      <Text>Copy the jar somewhere into your CLASSPATH, and make sure the Java3D extension is in your CLASSPATH too, like this...</Text>
    </Node>

  </Chapter>
  
  <Chapter>

    <Title>Usage</Title>
    <Text>Blah...</Text>

    <Node>
      <Title>Starting the Server</Title>
      <Text>java GoGridServer [gridsize]</Text>
    </Node>

    <Node>
      <Title>Starting the Client</Title>
      <Text>Make sure all relevant classes are in your CLASSPATH, then start the client with 
      java J3DApp [-s|--board-size boardsize]
                  [-m|--auto-moves automoves]
                  [-h|--server-host serverhost]</Text>
    </Node>

    <Node>
      <Title>Playing</Title>
      <Text></Text>
    </Node>

  </Chapter>
  
</Helpfile>